env:
  global:
    - secure: DkEriBeBkVPyD/yFGK/89+/6+RwJoUGtmTQSAFYH/vC3gKr+8lBYMMV07go4S7N/l6vI0Eb7IJVR/S9i7P1RfVPgFuJsIC8v3pk9Hah4WhkURTuYbW6bxZxySEC9duuoZ55HUNjqmQ78FSGkj1XmmATtxqT6+e7FSY5duJqRakZO3KYWQ1k7/uM6JKYbEepriJ2n6Nla4y9EWijRDukm9ocm+1iBaptigWWguU9o9Yg+MU2GfpV9SGlT+AJF5UZsxiKIfSzrzElL3v5rv2/zl6GF6815WbRdeNkCTnqj09rv75n/hDcPzqULr1IRyfi+8Xp0qiu0KxhxEqBUJeJAkE0/SORWkz66SxgFCg70SXQXV8KgXHyTFLU+GJplavO7Ra1ucxtkO2VOOx6bzbal0+N94YUCBtThLRMOr9VZId5gnHckzKvTMWHG9MzAqnZLGzTcpj4FeIwoIx7TYg2ELhPIwXRoXVYCJLmwLu6X6jrfSkCB6K6nL9XlWyou8AsTAfrhJ5zcsLrSTsnts4ZxG+ogJ3ldVyj1Y3OSL+4mbJRKw1vdGplLbzHBqbqOyI3Gv1WNk0NB9tPl8cSujJLEcth7NK93koAhlQ9k6Uaek3chfMRybc0MZnEzXc9jkOsqL7HAWYJuPdbn3aHm6Odrk2hbdDTtZX66kJwES3SmAZw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
