env:
  global:
    - secure: TRzwBbJbhrJg5MO2OtvE3UfhFK2ktMsDPS0xbw86ijzl3yCUjl8P9bzUeNEeU175ofvUlrnakFsEpNSmvbRVzFLxFUNugwVs3bzjLsO9g5R7U048HNG1nMAhYevxJkrp4FoRnz6zIR7wiags2bOgG3gfhemGD4UuUzWbXEdizXkLyCiZwGFQSTNPO+y1Kv9F+6jJt7rG1gOfzOMmj5XWEBdTgw4zDInnIUe+1Ib7RAGa7UNgSJuQbFno/ndd9U2WRPR7iSGMUyNsnC9lQHAbHjRsoxFScaoZmA8erqpVd36FDfcmkAHHH9nrBIXNP/vmQNH1HELdYlPXFIlOGgC8FvPbBrJoM2+/t4z4Mn2OlB9su1fisUCTFW4gPwstfexlT+Trzitf+x0PALVW4t4/6Zt9ipv2yrzFhaZeyVeLuvqEvTDibmbxnRv4/g1t/4PuNwtV5uL2xyCnBBQ3L21BPPwBVe5l2nrlO16gtLilLBd68h6eMvg0ijSq+17OiA1MMiMZhnEjaXe/ymg+VMEJCFCLMLNGf9pzeGznagWiFD1fNTSDq7R7tbZmDPc1FwRwQOP9HXe6HJCxZ6Ugc2d6JdzS9wXN48xE9MsF3ckrFnOEiv1Sz9mtRCs4qTYYfTEtcWVuk5TFhRkFZXXzYH9ktvdOABDszCv4zNkCkjqf78c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
