env:
  global:
    - secure: MCcL1fBprzN5+PFc4L0UGG4EJz9IX9QKeWiBfeC8rpMvUB1zo8KamxKDyFAJMpX1P9At1sJ3s4KIdq3eiGY+jMzrknd6iUuYOgnFQyM+lwSHz4Q6hiO8OEKExe9OyA5mZ6fpX9p1tah3cXISF4RcNKnwyXyiUQnKFWpKxM4ieU+hFk/6BAamCqRYzYQSHx+mX8S1NuFcM8c3kjs82S1F2BH1LT8dq2FfILZQZLZ4+G5q99LU8binkne9CAMIi0kXweD7Nnfbx4bABuyjD/ve9kHt++b43W18RdbkmqbBar48GFWKHjtD+mnFpJ9AhvYlcKGhhQ58Mkf8GrTCuZ+DsuCP5G2hZfI4B31UfkHUb3xm4+vP/7AkvMKCd4c07SvraF/pxpLRLDcg/3Sh027WjPZy5yl6P5ganNCxgRtH8ET6tsw+M9nO3uznHWbIwHZ80HhlZywfR4Yxhu7QkSliwrwsOXSga8EswHB9gPoGfiTSrPPTtJWOKMPp2A0VH9yMEZwEFzdaCXRWIe4/+BrVvwEJk0DLMpy8QR2XFE1dmGDGU56gFicxkrbOKhoK7zK8ByLU6X09OdINNIFvBeBYJLXc2MetQMNXHCR99GVW1iMH8aiRMow/Xdyb/yEOcNDsGYKqdUZQ0qAPnIYLq0GrEHjDrpeksBPSbVvDNATuTF0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
