env:
  global:
    - secure: oK/C/AD/IFEFGxuP27JB2pHCDzpJm/syY5V37efHqef7PTZVH4Bv8F+G1Cb3ScxsbF6O+fQyuUdWkWHo3X3us0n7GuPoFQHaeLFi9XloyVGSItnPxmq0+PyBSYk1J71Hy/bmArD4/vZoAy+UQ0ZyN2lr8/a0ZNxSGeO6pRcpoXmkHDxNv7YZS9wJzEoKO5W0LuUxWW7mjutaGbKhzsZYzoqOgqhgLtzYexFjPG50F73DC+Jaka4B4pfDnJTAxT6JXCHoznOHwV1WzrqUFsCNZc+agfbNGo6dgeSLAQPaZNCXFr7rQux9a6UrAhYvWUJkM2gQUAPd6yNGN2eQndZR7wXt7UX4HwhA2N8zkcMbsT4VVaFn06u9qSgvR9LYIpGHEFeTlfK/QyQwauTpGGLiH+6vyn9KDz/NFb3Khz/bDK+6VjWmB2uOmu+0RCjSsrRzWxwMcsmG1Se5+CraX34bAjbC2ukydojvm2ymQQeP08VE3G7EX7bt9czZ5e59h9z+qOFP/Jvp5G8bySEInT/0pNlISbFpGcFFdDurGAb4Cl660YgaQAZZcOK+bK/4f9JwbiBeFRxQ1nx5Mu/+K1i3XhosX/PIai5BgSXJ/GVsB2fDiJdeOCVadC/Jm4ecYNTLfFD2Fv4F0qgdfOIjrZsdsmgGHEhzEjTexfqb8n88JTE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
