env:
  global:
    - secure: nDrPS8nBs4EdytzO10AxPbAWMkSDPA9tXVskJXltErKyF6Amr7Mjd7lWXRvSv5HkbUSH3RnBfgALS8o3IkPhpQhU0onRs3lKxAqO4ChzERKt8TGjjwOjy1ed016zCuGh6wUcn5gVUP30zkukVf4zZWyTQoDKjw2iPdYxnixwm96J8Gd4A9aOR6usMKXbMwsHKMx8FuDfBE8TuxTBzX/dQKDgN32ZbRDogSh8Nv6cF+80BfajHBeV1ZeOXAIWS/41jWpKfZCJiy5VYbZcingxWhtLceJbto1wRqcHG/x7QsAQ8HalQVmHyOTzDLRdr9ZiUThs/WWdHiYklVbkEaEfYkJB9IDEdAxObEOYsP8Jr8NuvpRaEKbOu/qZNdmpwkGKmRV6AR/D1aeAxD5BGo7Et0Ubp3MhxaARFdQUy8+BOCZnuHnfmU5VV5PE6lo3b2rXoezj/1FmA4JZHpT/eNg2VEEd8mzsJLW5luPxx07DFDoSBrumCtWHS81tgQXD79wqveRFmFyEi9o8xlfDCC2rdGIjDgKggICOSZOC2XWfI+6oDW8PAPrI98ONOE7cod3WRlD4RtHC3/yFRt6p0qjgmp4M/DpRx/YQLW8VsqB80ZUkgfs0bGLRKWQ/Rx/yxxKX//1BCXrj0K7Mk869ZqQdZ3yni+OMGHFx8JnhAA0wqEE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
