env:
  global:
    - secure: G/MUDfHLG6xvLxCyWdwNwzdI3hI9cjlDHcZfZMZa8DFFIXZpNg4SQOq7cW7c+UPrdUqAIRAvg6VKXpmRMm8D1Zum7cy388nwhNNGWGvbMkvHYsKdsj4JvUmWHanFH33Bplmq0k++hMOrtxyznd3WoHBg1ne7ol6OjypYKSsnMajwng4Thfbi72X5ImtFzpcKvPrvKm0pC9YAxwefAFOAAxg6hwdOck4cehpP866VFC9DWQ0bkcv9XBbdYVRBG06CL3vPgtwQf3KTXIFfHkXU8tegbH/BfW9z3f6ezHJnsg6lrPK8Ozplfr+IWwLHF8zhpoyM7JYwaHPBq4vkGAnuppaja0VMRW6vIeYqPeJSii6Pc4yKHXeCEPZRap1/CXLC6Bf9GfuqpNnMyipozwl0gxTVWOf1uYSA1UdSiYIb1puFN5KNTvM0qs33lXfPMs1YF7zE4Iq0yrdsPJPkKDdnqAOj+yC1RWw+se1CJlp+Bn1RGiaZex0mYHjVH3U1TdiKRJ1HSldKeXRIQcZJY1QaVRwriAMDwsSMNjgv5hYRFxT1sTam9q947cO75kqlDxjB922bgbzSY3x6qgeNAMSfthUXyR6aezO/gvg2XphzOeHK5S9WPqusjkIcr7Esr5nrSkq0MJ8RqTvKL03TzbXGdrQ98r8VIdLR0gvLgf7mXGM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Ads_Disconnect.me
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
